wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.21
    is_jupyter_run: true
    python_version: 3.7.0
batch_size:
  desc: null
  value: 275.96758742138223
epochs:
  desc: null
  value: 330.74418441439343
learning_rate:
  desc: null
  value: 1.4555577603720755
