wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.21
    is_jupyter_run: true
    python_version: 3.7.0
batch_size:
  desc: null
  value: 282.56226134367716
epochs:
  desc: null
  value: 313.98353049678815
learning_rate:
  desc: null
  value: 0.7807001536168101
